version: 1.0.{build}-{branch}

os: Visual Studio 2015
configuration: Release
platform:
- x86

install:
- set PATH=%PATH%;C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin
  
build_script:
- set LDFLAGS=-static
- IF %PLATFORM%==x86 (set CXXFLAGS=-m32) ELSE (set CXXFLAGS=-m64)
- mingw32-make.exe -j4

after_build:
- strip 3dstex.exe
- cp 3dstex.exe 3dstex-win-%PLATFORM%.exe

test_script:
- mingw32-make.exe test
  
artifacts: 
- path: 3dstex-win-$(PLATFORM).exe
  name: release

deploy:
  provider: GitHub
  artifact: release
  auth_token:
    secure: ZPlcjsI5DN54Hup6VrIMj2WUCS5mX+WKLkHRlSmeXQ57sn4QWZ6AEZQLScYw267q
  on:
    appveyor_repo_tag: true
